services:
  - type: web
    name: trashtrail
    runtime: node
    rootDir: TrashTrail
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: "mongodb+srv://kpaswan9999_db_use:nVUndkVjnRVLJdD5@cluster0.ibkn9sw.mongodb.net/?appName=Cluster0"
      - key: NEXTAUTH_SECRET
        value: "7caeb453e970a0e3868ac1cd86f34567"
      - key: NEXTAUTH_URL
        value: "https://hackathon-project-trashtrail-waste-36ke.onrender.com"
      - key: GEMINI_API_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
